### ISSUE TITLE
upgrade to esp-idf v5.x branch

### ISSUE THREAD

**Issue by dennis4lora** [lora-gateway/esxp1302#17]
To upgrade to esp-idf v5.x branch, it's not difficult. However, there is a small change on the GCC side makes esxp1302 containing lots of lines needing to be fixed accordingly.

Per the migration guide: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/migration-guides/release-5.x/5.0/gcc.html#int32-t-and-uint32-t-for-xtensa-compiler

For example, we have two ways to display the value of `uint32_t value` as:
```diff
- printf("value = %u\n", value);
+ printf("value = %" PRIu32 "\n",  value);
```
or simply as:
```diff
- printf("value = %u\n", value);
+ printf("value = %lu\n",  value);
```
I'm not sure which is the better way to choose:
- the first way supports both esp-idf v4.x and v5.x branch.
- the second way is much simpler but only works on v5.x and fails for v4.x. 

So: **which way do you prefer?** should we keep v4.x support? your comments are welcome.

BTW: If you are interested, this [link](https://github.com/espressif/esp-idf/issues/9511) talked a lot of this issue.

**Comment by danielkucera** [comment]
I am already testing the updated version, this is my branch:
https://github.com/lora-gateway/esxp1302/compare/main...danielkucera:esxp1302:idf-update

Mine only ignores the warnings for format because of:
```
build_unflags = -Werror=all
```
which is the default for platformio. Is is the same for plain esp-idf?

But to your question - I don't see a particular reason to keep the old version supported.

**Comment by dennis4lora** [comment]
> which is the default for platformio. Is is the same for plain esp-idf?

I'm afraid not. Someone suggested that this can be done by adding `component_compile_options(-Wno-error=format= -Wno-format)` to **CMakeLists.txt**, but I can't make it correct to pass the compile step.

Anyway, I would like to fix it instead of bypass it. And I agree with your opinion that supporting v4.x isn't useful. So I'll follow the 2nd way.

**Comment by dennis4lora** [comment]
After changed some `%u` to `%lu` locally, I realized there are in fact two ways to do it (still takes `uint32_t` for example):

- %u --> %lu
- uint32_t --> unsigned int

`uint32_t` used to be interpreted as **unsigned int** and now becomes **unsigned long**, so very likely the size extends from 32-bit to 64-bit. It's no harm for the correctness, but I'm afraid it takes more space and not be used since 32-bit is already enough in the original intention.

So change `uint32_t` to **unsigned int** seems more reasonable.

@danielkucera: What's your opinion? Thanks.

**Comment by danielkucera** [comment]
good find, this is the best option IMO

**Comment by dennis4lora** [comment]
Great!!

And I'm sure:

```shell
 sed -i 's/uint32_t/unsigned int/g' *.c *.h 
```
is much quicker than manually working on the 1st way.  :rofl:

**Comment by dennis4lora** [comment]
I just checked the spec, and found that for both Xtensa (ESP32 based) and RISCV32 (ESP32C3 based), `int` takes 4 bytes, `long` also takes 4 bytes.

I also changed all `uint32_t` to `unsigned int` and compiled using PlatformIO, the produced firmware sizes match exactly before this change for both esp32 and esp32c3.

So there is no harm (but also no gain) for this change, but it's easy and needed for esp-idf v5.x branch, so let's do it this way.

**Comment by danielkucera** [comment]
Perfect.

**Comment by dennis4lora** [comment]
The updates has been done in branch [esp-idf-v5.x](https://github.com/lora-gateway/esxp1302/tree/esp-idf-v5.x).

I've tested the build with `esp-idf v5.2`, and `espressif32@6.7.0`, both OK, but the produced size is more than 10% bigger.   :frowning_face:

**Comment by danielkucera** [comment]
Hi @dennis4lora ,

how is this going? I think the increase is something we cannot avoid, esp-idf is getting more mature and there are many bug fixes so logically also the code base is growing.

Moreover, the v4 doesn't compile in platformio anymore: https://github.com/platformio/platform-espressif32/pull/1578

Can we push this somehow?

**Comment by dennis4lora** [comment]
Yes. I planned long ago to release a new version based on current main branch, then merge all other branches together for future development (mqtt, 4G/Ethernet etc.). I just postponed this a little too long...

I'll handle this in the coming days. Thanks for pushing me. :-)

**Comment by danielkucera** [comment]
Gentle ping. Can I help somehow?

**Comment by dennis4lora** [comment]
Thanks. I have just released `v0.9.0` (the esp32c3 binary firmware hasn't been tested yet).
I also merged/updated other branches. 😃

Since esp-idf v5.4.1 has been released a few months ago, I would like to update to that branch instead of the original planned v5.2 branch.
And how about the PlatformIO support? Should we also upgrade it to the latest version? Thanks.

**Comment by danielkucera** [comment]
Yes, I think we should go to the latest PIO which is 6.11.0

**Comment by danielkucera** [comment]
ping

**Comment by lora-gateway** [comment]
@danielkucera 

I've updated `dev` branch to latest `esp-idf` version (**v5.5.1**), and `espressif32` to **v6.11.0**.

I also tested `espressif32` **v6.12.0** but failed with this error:
```
Building .pio/build/nodo/bootloader.bin
Traceback (most recent call last):
  File "/home/dennis/.platformio/packages/tool-esptoolpy/esptool.py", line 41, in <module>
    import esptool
  File "/home/dennis/.platformio/packages/tool-esptoolpy/esptool/__init__.py", line 42, in <module>
    from esptool.bin_image import intel_hex_to_bin
  File "/home/dennis/.platformio/packages/tool-esptoolpy/esptool/bin_image.py", line 16, in <module>
    from intelhex import HexRecordError, IntelHex
ModuleNotFoundError: No module named 'intelhex'
```

There are discusses and solutions to fix this: https://github.com/platformio/platform-espressif32/issues/1632.

But consider v6.12.0 has been released 4 months ago, I expect v6.13.0 would be release soon, so I prefer to stay at v6.11.0 now, and update to v6.13.0 when it's ready. What's your opinion?

**Comment by danielkucera** [comment]
I agree, lets stay on 6.11.0 and later go to v6.13.0
